[package]
name = "data-scrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
reqwest = {workspace = true}
scraper = {workspace = true}
rand = {workspace = true}
serde = {workspace = true}